[project]
name = "image-quality-benchmark"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pillow>=12.0.0",
    "ssimulacra2>=0.3.0",
    "willow>=1.12.0",
]
